added special workspace setup for just one repo
ros-industrial/industrial_ci pull request #739
Opened 2021-08-12 15:16 UTC by dhled

Hello, 

I added this parsing command for url, if you just want to workspace extend with one private repo using ssh without creating a ".repos" or ".rosinstall" file (very niche case I guess).

Maybe there was already a way to achieve that but as I couldn't, I added this 'git+ssh'.

Does it make sense ?

Thank you !

2021-08-12 17:06 UTC, ipa-mdl requested changes
It should just work right away: `git+ssh://git@github.com/ros-industrial/industrial_ci.git#master`.

Please try it out and then we should extend the documentation.

2021-08-12 21:58 UTC, ipa-mdl commented
Actually, `git+ssh` is deprecated. I would rewrite to `ssh` as it is done for `file`.

2021-08-12 22:02 UTC, ipa-mdl commented on industrial_ci/src/workspace.sh
> +                ;;
```suggestion
```

2021-08-13 07:45 UTC, dhled commented on industrial_ci/src/workspace.sh
> +                ;;
Done

2021-08-13 07:45 UTC, dhled commented on industrial_ci/src/workspace.sh
>              'git+file'*|'git+http'*)
Done

2021-08-13 07:45 UTC, dhled commented
Thank you ! It should work with this :). I have added an example in the documentation.

2021-08-13 10:19 UTC, ipa-mdl commented on doc/index.rst
> +
```suggestion
```

?

2021-08-13 10:20 UTC, ipa-mdl commented on doc/index.rst
> +
```suggestion
To depend on a different repository of a private server using git and the SSH protocol:
::

  UPSTREAM_WORKSPACE='git+ssh://git@private.server.net/repository#branch'

```

2021-08-13 10:22 UTC, ipa-mdl commented
Shellcheck is failing for some time now, but I did not have the time yet to fix these issues.
Please update/squash your commits for now. I will try to fix shellcheck.

2021-08-13 11:26 UTC, dhled commented
Thank you, updated and squashed

2021-08-13 14:55 UTC, ipa-mdl approved these changes

2021-08-13 15:31 UTC, merged